name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: >-
        python -m
        pip install -r requirements.txt
        --user &&
        python -m
        pip install -r requirements_dev.txt
    - name: Run tests
      run: pytest -s tests